name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
        run: yarn install

      - name: Lint all projects
        run: yarn run lint

      - name: "Checking for Linting errors ..."
        run: "No Linting errors found , commiting ..."
        if: ${{ success() }}

      - name: Fail for lint errors
        run: exit 1
        if: ${{ failure() }}
